<a href="https://colab.research.google.com/github/abubakar1109/Full-Stack-Data-Scientist-BootCamp/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
var1=np.arange(15, 40)

In [ ]:
print(var1)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39]


In [ ]:
var2=np.arange(10, 26)

In [ ]:
print(var2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
even_aaray1=np.arange(2, 20,2)

In [ ]:
print(even_aaray1)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
even_aaray2=np.arange(34, 52,2)

In [ ]:
print(even_aaray2)

[34 36 38 40 42 44 46 48 50]


In [ ]:
matrix=np.stack((even_aaray1,even_aaray2))
print(matrix)

[[ 2  4  6  8 10 12 14 16 18]
 [34 36 38 40 42 44 46 48 50]]


In [ ]:
mat6x6=np.arange(0,36).reshape(6,6)

In [ ]:
print(mat6x6)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
a=mat6x6[3,2]
print(a)

20


In [ ]:
b=np.random.randn(5,2)
print(b)

[[ 0.6022941   0.36679609]
 [-0.27165744  0.36355322]
 [-0.78069498 -0.1471463 ]
 [-0.41106196 -0.18222694]
 [-0.30526792  0.56792715]]


In [ ]:
c=b[4,1]
print(c)

0.56792714868558


In [ ]:
min=np.min(b)
max=np.max(b)
std=np.std(b)
var=np.var(b)
mean=np.mean(b)
print("Mean = ",mean)
print("Variance = ",var)
print("Standard Deviation = ",std)
print("Minimum = ",min)
print("Maximum = ",max)

Mean =  -0.01974849956658048
Variance =  0.19484112552390473
Standard Deviation =  0.4414081167399448
Minimum =  -0.7806949822468874
Maximum =  0.602294097824149
